version: '3.1'

services:
    countries_db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_USER: application
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: quest_web
        volumes:
            - db_data:/var/lib/mysql